-- Hopetech: paste this complete file into the Supabase SQL Editor and click Run.
-- Creates new tables without deleting any existing student records.
BEGIN;
CREATE SCHEMA IF NOT EXISTS hopetech;
REVOKE ALL ON SCHEMA hopetech FROM PUBLIC;
CREATE TABLE IF NOT EXISTS hopetech.admins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password text NOT NULL
);
CREATE TABLE IF NOT EXISTS hopetech.sessions (
    token text PRIMARY KEY,
    admin_id bigint NOT NULL REFERENCES hopetech.admins(id) ON DELETE CASCADE,
    csrf text NOT NULL,
    expires bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS hopetech_sessions_expiry ON hopetech.sessions(expires);
CREATE TABLE IF NOT EXISTS hopetech.students (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    email text NOT NULL CHECK (char_length(email) BETWEEN 3 AND 254),
    phone text NOT NULL CHECK (char_length(phone) BETWEEN 7 AND 30),
    course text NOT NULL,
    schedule text NOT NULL CHECK (schedule IN ('weekday', 'weekend', 'online')),
    status text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')),
    notes text NOT NULL DEFAULT '' CHECK (char_length(notes) <= 2000),
    created timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    UNIQUE (email, course)
);
CREATE TABLE IF NOT EXISTS hopetech.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    email text NOT NULL CHECK (char_length(email) BETWEEN 3 AND 254),
    message text NOT NULL CHECK (char_length(message) BETWEEN 1 AND 3000),
    created timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE TABLE IF NOT EXISTS hopetech.limits (
    key text PRIMARY KEY,
    count integer NOT NULL,
    expires bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS hopetech_limits_expiry ON hopetech.limits(expires);

-- Browser API keys must never read, insert, or change these records directly.
-- The Vercel backend uses the private PostgreSQL connection as database owner.
ALTER TABLE hopetech.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE hopetech.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE hopetech.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE hopetech.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE hopetech.limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA hopetech FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA hopetech FROM PUBLIC;
DO $permissions$
DECLARE api_role text;
BEGIN
    FOREACH api_role IN ARRAY ARRAY['anon','authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = api_role) THEN
            EXECUTE format('REVOKE ALL ON SCHEMA hopetech FROM %I', api_role);
            EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA hopetech FROM %I', api_role);
            EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA hopetech FROM %I', api_role);
        END IF;
    END LOOP;
END
$permissions$;
COMMIT;
